const USER_ID = 'USER_ID';
const LOCATION = 'LOCATION';
const CIRCULAR_GEOFENCE = 'CIRCULAR_GEOFENCE';
const POLYGON_GEOFENCE = 'POLYGON_GEOFENCE';
const MARKER_POSITION = 'MARKER_POSITION';
const DOUBLE_MARKER = 'DOUBLE_MARKER';
const CENTER = 'CENTER';
const ZOOM = 'ZOOM';
const MARKERS = 'MARKERS';
const MYOFFICE_USERLANDMARK = 'MYOFFICE_USERLANDMARK';
const INFO_WINDOW = 'INFO_WINDOW';
const TOAST = 'TOAST';

export {
  USER_ID,
  LOCATION,
  CIRCULAR_GEOFENCE,
  POLYGON_GEOFENCE,
  MARKER_POSITION,
  DOUBLE_MARKER,
  CENTER,
  ZOOM,
  MARKERS,
  MYOFFICE_USERLANDMARK,
  INFO_WINDOW,
  TOAST
};
